version: '3.3'
services:
  day01:
    image: python:3.9
    volumes:
      - ./01-python:/code
    command: make -C /code

  day02:
    image: haskell:9.2
    volumes:
      - ./02-haskell:/code
    command: make -C /code

  day03:
    image: node:17.2.0
    volumes:
      - ./03-typescript:/code
    command: make -C /code install compile run clean

  day04:
    image: gcc:11.2
    volumes:
      - ./04-C:/code
    command: make -C /code

  day05:
    image: openjdk:18
    volumes:
      - ./05-java:/code
    command: /code/make.sh -C /code

  day06:
    image: rust:1.57
    volumes:
      - ./06-rust:/code
    command: make -C /code

  day07:
    image: ocaml/opam
    volumes:
      - ./07-ocaml:/code
    command: make -C /code

  day08:
    image: gcc:11.2
    volumes:
      - ./08-cpp:/code
    command: make -C /code

  day09:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.17.1"
      LEVEL_TYPE: "flat"
      SPAWN_MONSTERS: false
      OPS: "Zloutek1"
    volumes:
      - /tmp/aoc09:/data
      - ./09-minecraft:/data/world/datapacks/AoC

  day10:
    image: cmplopes/alpine-freepascal
    volumes:
      - ./10-pascal:/code
    command: /code/make.sh -C /code

  day11:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ./11-csharp:/code
    entrypoint: /code/make.sh -C /code

  day12:
    image: julia:1.6
    volumes:
      - ./12-julia:/code
    entrypoint: /code/make.sh -C /code

  day16:
    image: dart
    volumes:
      - ./16-dart:/code
    command: /code/make.sh -C /code