version: '3.3'
services:
  day01:
    image: python:3.9
    volumes:
      - ./01-python:/code
    command: make -C /code

  day02:
    image: haskell:9.2
    volumes:
      - ./02-haskell:/code
    command: make -C /code

  day03:
    image: node:17.2.0
    volumes:
      - ./03-typescript:/code
    command: make -C /code install compile run clean

  day04:
    image: gcc:11.2
    volumes:
      - ./04-C:/code
    command: make -C /code

  day05:
    image: openjdk:18
    volumes:
      - ./05-java:/code
    command: /code/make.sh -C /code

  day06:
    image: rust:1.57
    volumes:
      - ./06-rust:/code
    command: make -C /code

  day07:
    image: ocaml/opam
    volumes:
      - ./07-ocaml:/code
    command: make -C /code

  day08:
    image: gcc:11.2
    volumes:
      - ./08-cpp:/code
    command: make -C /code

  day09:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.17.1"
      LEVEL_TYPE: "flat"
      SPAWN_MONSTERS: false
      OPS: "Zloutek1"
    volumes:
      - /tmp/aoc09:/data
      - ./09-minecraft:/data/world/datapacks/AoC